package vista;
import Contenido.*;
import tda1.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexander
 */
public class FrmRegistroGeneral extends javax.swing.JFrame {
    private Lista<Expediente> expedientes;
    private Lista<Empleado> registroEmpleados;
    private DefaultTableModel tabla;
    /**
     * Creates new form FrmRegistroGeneral
     */
    public FrmRegistroGeneral() {
        initComponents();
    }
    
    public FrmRegistroGeneral(Lista pExpedientes, Lista pRegistroEmpleados) {
        initComponents();
        expedientes = pExpedientes;
        registroEmpleados = pRegistroEmpleados;
        
        tabla = new DefaultTableModel();
        tabla.addColumn("Cod. Emp.");
        tabla.addColumn("Area Emp.");
        tabla.addColumn("Prioridad");
        tabla.addColumn("Cód. Docum.");
        tabla.addColumn("Tipo Docum.");
        tabla.addColumn("Asunto");
        tabla.addColumn("Estado");
        tabla.addColumn("Fecha");
        tabla.addColumn("Cód. Usuario");
        tabla.addColumn("Empleado Dest.");
        tabla.addColumn("Área Destino");
        this.tblRegGeneralDocumentos.setModel(tabla);
        llenarTabla();
    }
    
    public void llenarTabla(){
        for(int i=1; i<= expedientes.longitud() && i<= registroEmpleados.longitud(); i++){
            String[] fila = new String[11];
            fila[0] = registroEmpleados.iesimo(i).getCodEMP();
            fila[1] = registroEmpleados.iesimo(i).getAreaEMP();
            fila[2] = expedientes.iesimo(i).getPrioridad();
            fila[3] = expedientes.iesimo(i).getCodDOC();
            fila[4] = expedientes.iesimo(i).getTipoDOC();
            fila[5] = expedientes.iesimo(i).getAsuntoDOC();
            fila[6] = expedientes.iesimo(i).getEstadoDOC();
            fila[7] = expedientes.iesimo(i).getFecha();
            fila[8] = expedientes.iesimo(i).getCodUSER();
            fila[9] = expedientes.iesimo(i).getDestinoEMP();
            fila[10] = expedientes.iesimo(i).getDestinoArea();
            tabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegGeneralDocumentos = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Documentos");

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Registro de Documentos");

        tblRegGeneralDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegGeneralDocumentos);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegGeneralDocumentos;
    // End of variables declaration//GEN-END:variables
}
